# Generated by Django 5.2.4 on 2025-07-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('contactReason', models.CharField(choices=[('partnership', 'Partnership Inquiry'), ('guide-registration', 'Guide Registration'), ('general-question', 'General Question'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=30)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
