kind: Deployment 
apiVersion: apps/v1
metadata: 
  name: local-dap
  namespace: local

spec:
  replicas: 5
  selector:
    matchLabels:
      app: local
  template:
    metadata:
      labels: 
        app: local
    spec:
      containers:
      - name: local
        image: qadargada2/local:latest
        ports:
        - containerPort: 8000


