kind: Deployment 
apiVersion: apps/v1
metadata: 
  name: django-deployment 
  namespace: django

spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels: 
        app: django-app
    spec:
      containers:
      - name: django
        image: addico786/django-app:latest
        ports:
        - containerPort: 8000


